// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: tracklist_tracks.sql

package database

import (
	"context"
)

const addTracklistTrack = `-- name: AddTracklistTrack :exec
INSERT INTO "tracklist_tracks" (
  "id",
  "tracklist_id",
  "track_id",
  "track_number"
)
VALUES ($1, $2, $3, $4)
`

type AddTracklistTrackParams struct {
	ID          string
	TracklistID string
	TrackID     string
	TrackNumber int32
}

func (q *Queries) AddTracklistTrack(ctx context.Context, arg AddTracklistTrackParams) error {
	_, err := q.db.Exec(ctx, addTracklistTrack,
		arg.ID,
		arg.TracklistID,
		arg.TrackID,
		arg.TrackNumber,
	)
	return err
}
