// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account_tokens.sql

package database

import (
	"context"
	"time"
)

const consumeAccountToken = `-- name: ConsumeAccountToken :one
DELETE FROM account_tokens
WHERE token_hash = $1 AND purpose = $2 AND expires_at > NOW()
RETURNING user_id
`

type ConsumeAccountTokenParams struct {
	TokenHash []byte
	Purpose   string
}

func (q *Queries) ConsumeAccountToken(ctx context.Context, arg ConsumeAccountTokenParams) (string, error) {
	row := q.db.QueryRow(ctx, consumeAccountToken, arg.TokenHash, arg.Purpose)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const createAccountToken = `-- name: CreateAccountToken :exec
INSERT INTO account_tokens (token_hash, user_id, purpose, expires_at) VALUES ($1, $2, $3, $4)
`

type CreateAccountTokenParams struct {
	TokenHash []byte
	UserID    string
	Purpose   string
	ExpiresAt time.Time
}

func (q *Queries) CreateAccountToken(ctx context.Context, arg CreateAccountTokenParams) error {
	_, err := q.db.Exec(ctx, createAccountToken,
		arg.TokenHash,
		arg.UserID,
		arg.Purpose,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredAccountTokens = `-- name: DeleteExpiredAccountTokens :exec
DELETE FROM account_tokens WHERE expires_at <= NOW()
`

func (q *Queries) DeleteExpiredAccountTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredAccountTokens)
	return err
}

const deleteUserAccountTokens = `-- name: DeleteUserAccountTokens :exec
DELETE FROM account_tokens WHERE user_id = $1 AND purpose = $2
`

type DeleteUserAccountTokensParams struct {
	UserID  string
	Purpose string
}

func (q *Queries) DeleteUserAccountTokens(ctx context.Context, arg DeleteUserAccountTokensParams) error {
	_, err := q.db.Exec(ctx, deleteUserAccountTokens, arg.UserID, arg.Purpose)
	return err
}

const getAccountToken = `-- name: GetAccountToken :one
SELECT user_id FROM account_tokens
WHERE token_hash = $1 AND purpose = $2 AND expires_at > NOW()
`

type GetAccountTokenParams struct {
	TokenHash []byte
	Purpose   string
}

func (q *Queries) GetAccountToken(ctx context.Context, arg GetAccountTokenParams) (string, error) {
	row := q.db.QueryRow(ctx, getAccountToken, arg.TokenHash, arg.Purpose)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}
