// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Track struct {
	ID               string
	Artist           string
	Name             string
	Genre            string
	BPM              float64
	Key              string
	Created          time.Time
	Updated          time.Time
	FtsNameAndArtist pgtype.TSVector
}

type Tracklist struct {
	ID      string
	Name    string
	Date    time.Time
	Artwork string
	URL     string
	Created time.Time
	Updated time.Time
	OwnerID pgtype.UUID
}

type User struct {
	ID              string
	Email           string
	PasswordHash    string
	DisplayName     string
	EmailVerifiedAt pgtype.Timestamptz
	Created         time.Time
	Updated         time.Time
}
