// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tracklists.sql

package database

import (
	"context"
	"time"
)

const addTracklist = `-- name: AddTracklist :one
INSERT INTO tracklists (id, name, url, artwork, date, owner_id, created, updated)
VALUES ($1, $2, $3, $4, $5, $6, NOW(), NOW())
RETURNING id, name, date, artwork, url, created, updated, owner_id
`

type AddTracklistParams struct {
	ID      string
	Name    string
	URL     string
	Artwork string
	Date    time.Time
	OwnerID string
}

func (q *Queries) AddTracklist(ctx context.Context, arg AddTracklistParams) (*Tracklist, error) {
	row := q.db.QueryRow(ctx, addTracklist,
		arg.ID,
		arg.Name,
		arg.URL,
		arg.Artwork,
		arg.Date,
		arg.OwnerID,
	)
	var i Tracklist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Date,
		&i.Artwork,
		&i.URL,
		&i.Created,
		&i.Updated,
		&i.OwnerID,
	)
	return &i, err
}

const countTracklists = `-- name: CountTracklists :one
SELECT count(*) FROM tracklists
WHERE ($1::uuid IS NULL OR owner_id = $1)
  AND ($2::uuid IS NULL OR EXISTS (
    SELECT 1 FROM tracklist_tracks
    WHERE tracklist_tracks.tracklist_id = tracklists.id AND tracklist_tracks.track_id = $2
  ))
`

type CountTracklistsParams struct {
	OwnerID *string
	TrackID *string
}

func (q *Queries) CountTracklists(ctx context.Context, arg CountTracklistsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTracklists, arg.OwnerID, arg.TrackID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteTracklist = `-- name: DeleteTracklist :execrows
DELETE FROM tracklists WHERE id = $1 AND owner_id = $2
`

type DeleteTracklistParams struct {
	ID      string
	OwnerID string
}

func (q *Queries) DeleteTracklist(ctx context.Context, arg DeleteTracklistParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTracklist, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTracklistWithTracks = `-- name: GetTracklistWithTracks :many
SELECT tracklists.id, tracklists.name, tracklists.date, tracklists.artwork, tracklists.url, tracklists.created, tracklists.updated, tracklists.owner_id, tracks.id, tracks.artist, tracks.name, tracks.genre, tracks.bpm, tracks.key, tracks.created, tracks.updated, tracks.fts_name_and_artist, users.display_name AS owner_display_name
FROM tracklists
JOIN users ON users.id = tracklists.owner_id
JOIN tracklist_tracks ON tracklist_tracks.tracklist_id = tracklists.id
JOIN tracks ON tracks.id = tracklist_tracks.track_id
WHERE tracklists.id = $1
ORDER BY tracklist_tracks.track_number ASC
`

type GetTracklistWithTracksRow struct {
	Tracklist        Tracklist
	Track            Track
	OwnerDisplayName string
}

func (q *Queries) GetTracklistWithTracks(ctx context.Context, id string) ([]*GetTracklistWithTracksRow, error) {
	rows, err := q.db.Query(ctx, getTracklistWithTracks, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetTracklistWithTracksRow{}
	for rows.Next() {
		var i GetTracklistWithTracksRow
		if err := rows.Scan(
			&i.Tracklist.ID,
			&i.Tracklist.Name,
			&i.Tracklist.Date,
			&i.Tracklist.Artwork,
			&i.Tracklist.URL,
			&i.Tracklist.Created,
			&i.Tracklist.Updated,
			&i.Tracklist.OwnerID,
			&i.Track.ID,
			&i.Track.Artist,
			&i.Track.Name,
			&i.Track.Genre,
			&i.Track.BPM,
			&i.Track.Key,
			&i.Track.Created,
			&i.Track.Updated,
			&i.Track.FtsNameAndArtist,
			&i.OwnerDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTracklists = `-- name: GetTracklists :many
SELECT tracklists.id, tracklists.name, tracklists.date, tracklists.artwork, tracklists.url, tracklists.created, tracklists.updated, tracklists.owner_id, users.display_name AS owner_display_name,
  (SELECT count(*) FROM tracklist_tracks WHERE tracklist_id = tracklists.id) AS track_count
FROM tracklists JOIN users ON users.id = tracklists.owner_id
WHERE ($1::uuid IS NULL OR tracklists.owner_id = $1)
  AND ($2::uuid IS NULL OR EXISTS (
    SELECT 1 FROM tracklist_tracks
    WHERE tracklist_tracks.tracklist_id = tracklists.id AND tracklist_tracks.track_id = $2
  ))
ORDER BY tracklists.date DESC, tracklists.id
OFFSET $3 LIMIT $4
`

type GetTracklistsParams struct {
	OwnerID    *string
	TrackID    *string
	PageOffset int32
	PageLimit  int32
}

type GetTracklistsRow struct {
	Tracklist        Tracklist
	OwnerDisplayName string
	TrackCount       int64
}

func (q *Queries) GetTracklists(ctx context.Context, arg GetTracklistsParams) ([]*GetTracklistsRow, error) {
	rows, err := q.db.Query(ctx, getTracklists,
		arg.OwnerID,
		arg.TrackID,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetTracklistsRow{}
	for rows.Next() {
		var i GetTracklistsRow
		if err := rows.Scan(
			&i.Tracklist.ID,
			&i.Tracklist.Name,
			&i.Tracklist.Date,
			&i.Tracklist.Artwork,
			&i.Tracklist.URL,
			&i.Tracklist.Created,
			&i.Tracklist.Updated,
			&i.Tracklist.OwnerID,
			&i.OwnerDisplayName,
			&i.TrackCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOwnedTracklist = `-- name: LockOwnedTracklist :one
SELECT id, name, date, artwork, url, created, updated, owner_id FROM tracklists WHERE id = $1 AND owner_id = $2 FOR UPDATE
`

type LockOwnedTracklistParams struct {
	ID      string
	OwnerID string
}

func (q *Queries) LockOwnedTracklist(ctx context.Context, arg LockOwnedTracklistParams) (*Tracklist, error) {
	row := q.db.QueryRow(ctx, lockOwnedTracklist, arg.ID, arg.OwnerID)
	var i Tracklist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Date,
		&i.Artwork,
		&i.URL,
		&i.Created,
		&i.Updated,
		&i.OwnerID,
	)
	return &i, err
}

const updateTracklist = `-- name: UpdateTracklist :one
UPDATE tracklists
SET name = $1, url = $2, date = $3, updated = NOW()
WHERE id = $4 AND owner_id = $5
RETURNING id, name, date, artwork, url, created, updated, owner_id
`

type UpdateTracklistParams struct {
	Name    string
	URL     string
	Date    time.Time
	ID      string
	OwnerID string
}

func (q *Queries) UpdateTracklist(ctx context.Context, arg UpdateTracklistParams) (*Tracklist, error) {
	row := q.db.QueryRow(ctx, updateTracklist,
		arg.Name,
		arg.URL,
		arg.Date,
		arg.ID,
		arg.OwnerID,
	)
	var i Tracklist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Date,
		&i.Artwork,
		&i.URL,
		&i.Created,
		&i.Updated,
		&i.OwnerID,
	)
	return &i, err
}
