// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package datastore

import (
	"time"
)

type Tracklist struct {
	ID      string
	Name    string
	Date    time.Time
	Artwork string
	URL     string
	Created time.Time
	Updated time.Time
}
