-- UP

CREATE TABLE tracks (
  id     UUID PRIMARY KEY,
  artist VARCHAR (256) NOT NULL,
  name   VARCHAR (256) NOT NULL,
  genre  VARCHAR (128) NOT NULL,
  bpm    INTEGER NOT NULL,
  key    VARCHAR (8) NOT NULL
);

-- DOWN

DROP TABLE IF EXISTS tracks CASCADE;
