-- UP

CREATE TABLE tracklists (
  id      UUID PRIMARY KEY,
  name    VARCHAR(256) NOT NULL,
  date    TIMESTAMP NOT NULL,
  created TIMESTAMP NOT NULL,
  updated TIMESTAMP NOT NULL
);

-- DOWN

DROP TABLE IF EXISTS tracklists CASCADE;
